---
name: CI

on: [push, pull_request]

jobs:

  test:
    name: Unit tests
    strategy:
      matrix:
        python-version: [2.7, 3.6, 3.7]
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
      - name: run tests
        run: python -m pytest tests/

  deploy:
    name: Deploy to GitHub and PyPI
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master' && github.repository_owner == 'ladybug-tools'
    steps:
      - uses: actions/checkout@v2
      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: set up node  # we need node for for semantic release
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.2.0
      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
      - name: install semantic-release
        run:
          npm install @semantic-release/exec
      - name: run semantic release
        run:
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
